Update feature_tracker.cpp
Reverted back to original VINS feature extracture due to error in cuda I was not able to solve: 
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.5.5) /opt/opencv_contrib/modules/cudafilters/src/cuda/row_filter.hpp:169: error: (-217:Gpu API call) no kernel image is available for execution on the device in function 'caller'